site_name: Resumos
copyright: 2023 Luiza H. Moretti
repo_name: RESUMOS
repo_url: https://github.com/nszchagas/RESUMOS

theme:
  name: material
#  icon:
#    logo: material/library-house
  features:
    - content.code.annotate
    - content.code.copy
 
  favicon: assets/icon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: dark purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      toggle:
        icon: material/brightness-4
        name: Light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
   - attr_list
   - pymdownx.caret
   - pymdownx.mark
   - pymdownx.tilde
   - footnotes
   - pymdownx.smartsymbols
   - pymdownx.tasklist:
      clickable_checkbox: true

nav:
  - Empreendedorismo:
    - Informações Gerais: empreendedorismo/m4d1_empreendedorismo.md
    - Conteúdo:
      - Unidade 1: empreendedorismo/emp_conteudo1.md
      - Unidade 2: empreendedorismo/emp_conteudo2.md
      - Unidade 3: empreendedorismo/emp_conteudo3.md
      - Unidade 4: empreendedorismo/emp_conteudo4.md
    - Avaliações: empreendedorismo/emp_avaliacoes.md
    - Projeto: empreendedorismo/emp_projeto.md

